# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dbe903f19e60e7cc712bfb2cff6ef3d4f8ad555881bcff230035c3008296aa95a3fda8723be54ea7d4d92208cc2d414d9a61cef34ba7c4c13acc9c5fe6b92cf

test:
  secret_key_base: 8597685155fcd3da27a073e3f3e3a7a71bbb6af8328e29b68f3ad8709dd94fe081823d68c319f455f606b2f41081d73b4d06f195c024849188cac4f471b1700e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
